[theme]
primaryColor = "#00E5FF"
backgroundColor = "#050816"
secondaryBackgroundColor = "#0E1628"
textColor = "#F4FBFF"
font = "sans serif"

[server]
headless = true
runOnSave = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[runner]
fastReruns = true
magicEnabled = true